# On part de l'image du camarade
FROM stephanenawrat/welcome-to-docker:v2

# On ajoute tes informations pour le suivi
LABEL maintainer="theubald"
LABEL original_author="stephanenawrat"

# On peut ajouter un petit fichier texte à l'intérieur pour marquer le coup
RUN echo "Projet modifié par theubald" > /info_modif.txt